# This is a basic workflow to help you get started with Actions

name: Example Workflow For Demonstration of Coda Pack

# Controls when the workflow will run
on:
  workflow_dispatch:
  repository_dispatch:
    types: [coda-action]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      run: |
        echo "Hello World from Coda"